### ISSUE TITLE
No Tunnel URL generated

### ISSUE THREAD

**Issue by VeXHarbinger** [saharmor/dalle-playground#21]
![DALL-E-Playground-Backend-Colaboratory](https://user-images.githubusercontent.com/830407/172521516-c48d97ab-a5a5-4cfd-afc0-dcdba2aac61c.png)

AFAIK all the dependencies installed and the code runs as expected.  However, when I run the 4th cell, it just keeps spinning and I see no URL generated as described.  Is the last cell supposed to contain the URI after I hit play?  I'm sure the mistake is mine or that there is a step most folks would know to get colab running that I am unaware of

**Comment by SeraphimRP** [comment]
It appears that loca.lt is down, which is causing the issue.

**Comment by VeXHarbinger** [comment]
Actually I fixed this by rerunning the !npm install -g localtunnel command
It now generated the URI, surprised there wasn't an error though

**Comment by SeraphimRP** [comment]
loca.lt appears to be back up now as well, so maybe just a timing of both :)

**Comment by marcellopajntar** [comment]
ehi @SeraphimRP :) unfortunately the problem persist for me, how can i solve?

**Comment by VeXHarbinger** [comment]
> ehi @SeraphimRP :) unfortunately the problem persist for me, how can i solve?
Did you try '!npm install -g localtunnel' to see if it will install or throws an error

**Comment by SeraphimRP** [comment]
I'm not a support person here either, I replied to this since I was also having the issue at the time when VeX reported it, and I noticed that loca.lt was down. It started working after our second two replies but I haven't attempted to use this since.

**Comment by VeXHarbinger** [comment]
> Woops wrong quote.  Sry

**Comment by VeXHarbinger** [comment]
Howdy @marcellopajntar,
Did you try **'!npm install -g localtunnel'** to see if it will install or throws an error?
Once I pasted that into a cell and ran it, my URL was generated. when I ran the Backend code block.
**What is the error you are seeing reported in any of the processes?**
