### ISSUE TITLE
Docker AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft

### ISSUE THREAD

**Issue by cdmichaelb** [saharmor/dalle-playground#83]
`Traceback (most recent call last):

  File "app.py", line 18, in <module>

    from dalle_model import DalleModel

  File "/app/dalle_model.py", line 5, in <module>

    import jax

  File "/usr/local/lib/python3.8/dist-packages/jax/__init__.py", line 116, in <module>

    from .experimental.maps import soft_pmap as soft_pmap

  File "/usr/local/lib/python3.8/dist-packages/jax/experimental/maps.py", line 26, in <module>

    from .. import numpy as jnp

  File "/usr/local/lib/python3.8/dist-packages/jax/numpy/__init__.py", line 19, in <module>

    from . import fft as fft

  File "/usr/local/lib/python3.8/dist-packages/jax/numpy/fft.py", line 17, in <module>

    from jax._src.numpy.fft import (

  File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/fft.py", line 19, in <module>

    from jax import lax

  File "/usr/local/lib/python3.8/dist-packages/jax/lax/__init__.py", line 332, in <module>

    from jax._src.lax.fft import (

  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lax/fft.py", line 145, in <module>

    xla.backend_specific_translations['cpu'][fft_p] = pocketfft.pocketfft

AttributeError: module 'jaxlib.pocketfft' has no attribute 'pocketfft'`

**Comment by hibby50** [comment]
Same issue here

**Comment by cdmichaelb** [comment]
@hibby50 

Fixed with #79

**Comment by JoshWarn** [comment]
Still seem to be having this issue while working with MEGA.

**Comment by Larry-Schultz** [comment]
I manually changed my Dockerfile to replicate the changes in #79 and this issue still happens on startup.
